using AeroTech.Messages.Ordering.Enums;

namespace AeroTech.Ordering.Application.OrderAggregate.Services.Exchange
{
    public sealed record ExchangeOutcome(
        long OrderId,
        long OperationId,
        OrderChangeType CommercialResult,
        ServicingOperationKind TechnicalOperation,
        long PredecessorElectronicTicketId,
        string PredecessorDocumentNumber,
        int PredecessorDocumentVersion,
        long? SuccessorElectronicTicketId,
        string? SuccessorDocumentNumber,
        int? SuccessorDocumentVersion,
        IReadOnlyList<long> ChangedOrderServiceIds,
        IReadOnlyList<ExchangeCouponOutcome> Coupons,
        long? OrderChangeId,
        long? PriceChangeSetId,
        int CommercialVersion,
        long FinancialSequence,
        long ObligationVersion,
        decimal CustomerTotal,
        DocumentExchangeEligibilityOutcome? EligibilityOutcome,
        ProviderOperationOutcome ReservationChangeOutcome,
        ProviderOperationOutcome DocumentExchangeOutcome,
        string? ProviderExchangeReference,
        ExchangeDocumentOutcome DocumentOutcome,
        ServicingOperationStatus OperationStatus,
        ChangeMonetaryOutcome? MonetaryOutcome,
        decimal? AddCollectAmount,
        int? AddCollectCurrencyId,
        ExchangeFundingState FundingState,
        string? FundingProviderReference,
        decimal? MonetaryAmount,
        int? MonetaryCurrencyId,
        string? MonetaryDisposition,
        ExchangeMonetaryState MonetaryState,
        string? MonetaryProviderReference,
        string? ResidualInstrumentReference,
        ResidualInstrumentKind? ResidualInstrument,
        bool RequiresReconciliation,
        bool DeferredToExpandedExchange,
        string? DeferralReason,
        bool IsReplay);
}
